package com.erp.demo.model;
// Generated 2024�~2��28�� �W��3:00:56 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * Dispatchment generated by hbm2java
 */
public class Dispatchment implements java.io.Serializable {

	private String did;
	private int id;
	private String oid;
	private Serializable dispEid1;
	private Serializable dispEid2;
	private char status;
	private Timestamp createTime;
	private Timestamp updateTime;
	private Serializable updateName;

	public Dispatchment() {
	}

	public Dispatchment(int id, String oid, Serializable dispEid1, Serializable dispEid2, char status,
			Timestamp createTime, Timestamp updateTime, Serializable updateName) {
		this.id = id;
		this.oid = oid;
		this.dispEid1 = dispEid1;
		this.dispEid2 = dispEid2;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.updateName = updateName;
	}

	public String getDid() {
		return this.did;
	}

	public void setDid(String did) {
		this.did = did;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public Serializable getDispEid1() {
		return this.dispEid1;
	}

	public void setDispEid1(Serializable dispEid1) {
		this.dispEid1 = dispEid1;
	}

	public Serializable getDispEid2() {
		return this.dispEid2;
	}

	public void setDispEid2(Serializable dispEid2) {
		this.dispEid2 = dispEid2;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Timestamp getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}

	public Serializable getUpdateName() {
		return this.updateName;
	}

	public void setUpdateName(Serializable updateName) {
		this.updateName = updateName;
	}

}
