package com.erp.demo.model;
// Generated 2024�~2��28�� �W��3:00:56 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;

/**
 * EmRole generated by hbm2java
 */
public class EmRole implements java.io.Serializable {

	private String roleCode;
	private Serializable roleName;
	private char memberSelectR1;

	public EmRole() {
	}

	public EmRole(String roleCode, Serializable roleName, char memberSelectR1) {
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.memberSelectR1 = memberSelectR1;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public Serializable getRoleName() {
		return this.roleName;
	}

	public void setRoleName(Serializable roleName) {
		this.roleName = roleName;
	}

	public char getMemberSelectR1() {
		return this.memberSelectR1;
	}

	public void setMemberSelectR1(char memberSelectR1) {
		this.memberSelectR1 = memberSelectR1;
	}

}
