package com.erp.demo.model;
// Generated 2024�~2��28�� �W��3:00:56 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private String mid;
	private int id;
	private String userName;
	private String password;
	private String name;
	private Serializable sex;
	private String nationalld;
	private Date birthDate;
	private String cellphone;
	private String landlineprefix;
	private String landline;
	private String email;
	private byte postalCode;
	private Serializable address;
	private Serializable footnote;
	private Timestamp createTime;
	private Timestamp updateTime;
	private Serializable updateName;

	public Member() {
	}

	public Member(int id, String userName, String password, String name, Serializable sex, String nationalld,
			Date birthDate, String cellphone, String landlineprefix, String landline, String email, byte postalCode,
			Serializable address, Serializable footnote, Timestamp createTime, Timestamp updateTime,
			Serializable updateName) {
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.name = name;
		this.sex = sex;
		this.nationalld = nationalld;
		this.birthDate = birthDate;
		this.cellphone = cellphone;
		this.landlineprefix = landlineprefix;
		this.landline = landline;
		this.email = email;
		this.postalCode = postalCode;
		this.address = address;
		this.footnote = footnote;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.updateName = updateName;
	}

	public String getMid() {
		return this.mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Serializable getSex() {
		return this.sex;
	}

	public void setSex(Serializable sex) {
		this.sex = sex;
	}

	public String getNationalld() {
		return this.nationalld;
	}

	public void setNationalld(String nationalld) {
		this.nationalld = nationalld;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getLandlineprefix() {
		return this.landlineprefix;
	}

	public void setLandlineprefix(String landlineprefix) {
		this.landlineprefix = landlineprefix;
	}

	public String getLandline() {
		return this.landline;
	}

	public void setLandline(String landline) {
		this.landline = landline;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public byte getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(byte postalCode) {
		this.postalCode = postalCode;
	}

	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	public Serializable getFootnote() {
		return this.footnote;
	}

	public void setFootnote(Serializable footnote) {
		this.footnote = footnote;
	}

	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Timestamp getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}

	public Serializable getUpdateName() {
		return this.updateName;
	}

	public void setUpdateName(Serializable updateName) {
		this.updateName = updateName;
	}

}
