package com.erp.demo.model;
// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

/**
 * OrderItem generated by hbm2java
 */
public class OrderItem implements java.io.Serializable {

	private Integer id;
	private String oid;
	private String pid;
	private int quantity;

	public OrderItem() {
	}

	public OrderItem(String oid, String pid, int quantity) {
		this.oid = oid;
		this.pid = pid;
		this.quantity = quantity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
