package com.erp.demo.model;
// Generated 2024�~2��28�� �W��3:00:56 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private String oid;
	private int id;
	private String mid;
	private int status;
	private Integer amount;
	private Integer total;
	private String paymentCode;
	private Serializable shippingMethod;
	private Serializable recipient;
	private String cellphone;
	private String landlineprefix;
	private String landline;
	private String email;
	private int postalCode;
	private Serializable address;
	private String did;
	private Serializable footnote;
	private Timestamp createTime;
	private Timestamp updateTime;
	private Serializable updateName;

	public Order() {
	}

	public Order(int id, String mid, int status, Integer amount, Integer total, String paymentCode,
			Serializable shippingMethod, Serializable recipient, String cellphone, String landlineprefix,
			String landline, String email, int postalCode, Serializable address, String did, Serializable footnote,
			Timestamp createTime, Timestamp updateTime, Serializable updateName) {
		this.id = id;
		this.mid = mid;
		this.status = status;
		this.amount = amount;
		this.total = total;
		this.paymentCode = paymentCode;
		this.shippingMethod = shippingMethod;
		this.recipient = recipient;
		this.cellphone = cellphone;
		this.landlineprefix = landlineprefix;
		this.landline = landline;
		this.email = email;
		this.postalCode = postalCode;
		this.address = address;
		this.did = did;
		this.footnote = footnote;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.updateName = updateName;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getMid() {
		return this.mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public String getPaymentCode() {
		return this.paymentCode;
	}

	public void setPaymentCode(String paymentCode) {
		this.paymentCode = paymentCode;
	}

	public Serializable getShippingMethod() {
		return this.shippingMethod;
	}

	public void setShippingMethod(Serializable shippingMethod) {
		this.shippingMethod = shippingMethod;
	}

	public Serializable getRecipient() {
		return this.recipient;
	}

	public void setRecipient(Serializable recipient) {
		this.recipient = recipient;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getLandlineprefix() {
		return this.landlineprefix;
	}

	public void setLandlineprefix(String landlineprefix) {
		this.landlineprefix = landlineprefix;
	}

	public String getLandline() {
		return this.landline;
	}

	public void setLandline(String landline) {
		this.landline = landline;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}

	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	public String getDid() {
		return this.did;
	}

	public void setDid(String did) {
		this.did = did;
	}

	public Serializable getFootnote() {
		return this.footnote;
	}

	public void setFootnote(Serializable footnote) {
		this.footnote = footnote;
	}

	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Timestamp getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}

	public Serializable getUpdateName() {
		return this.updateName;
	}

	public void setUpdateName(Serializable updateName) {
		this.updateName = updateName;
	}

}
