package com.erp.demo.model;
// Generated 2024�~2��28�� �W��3:00:56 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;

/**
 * Ostatus generated by hbm2java
 */
public class Ostatus implements java.io.Serializable {

	private int ostatusCode;
	private Serializable ostatusName;
	private Serializable ostatusDesc;

	public Ostatus() {
	}

	public Ostatus(int ostatusCode, Serializable ostatusName, Serializable ostatusDesc) {
		this.ostatusCode = ostatusCode;
		this.ostatusName = ostatusName;
		this.ostatusDesc = ostatusDesc;
	}

	public int getOstatusCode() {
		return this.ostatusCode;
	}

	public void setOstatusCode(int ostatusCode) {
		this.ostatusCode = ostatusCode;
	}

	public Serializable getOstatusName() {
		return this.ostatusName;
	}

	public void setOstatusName(Serializable ostatusName) {
		this.ostatusName = ostatusName;
	}

	public Serializable getOstatusDesc() {
		return this.ostatusDesc;
	}

	public void setOstatusDesc(Serializable ostatusDesc) {
		this.ostatusDesc = ostatusDesc;
	}

}
