package com.erp.demo.model;
// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

/**
 * Ostatus generated by hbm2java
 */
public class Ostatus implements java.io.Serializable {

	private int ostatusCode;
	private String ostatusName;
	private String ostatusDesc;

	public Ostatus() {
	}

	public Ostatus(int ostatusCode, String ostatusName, String ostatusDesc) {
		this.ostatusCode = ostatusCode;
		this.ostatusName = ostatusName;
		this.ostatusDesc = ostatusDesc;
	}

	public int getOstatusCode() {
		return this.ostatusCode;
	}

	public void setOstatusCode(int ostatusCode) {
		this.ostatusCode = ostatusCode;
	}

	public String getOstatusName() {
		return this.ostatusName;
	}

	public void setOstatusName(String ostatusName) {
		this.ostatusName = ostatusName;
	}

	public String getOstatusDesc() {
		return this.ostatusDesc;
	}

	public void setOstatusDesc(String ostatusDesc) {
		this.ostatusDesc = ostatusDesc;
	}

}
