package com.erp.demo.model;
// Generated 2024�~2��28�� �W��3:00:56 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;

/**
 * PostalCode generated by hbm2java
 */
public class PostalCode implements java.io.Serializable {

	private int postalCode;
	private Serializable county;
	private Serializable district;

	public PostalCode() {
	}

	public PostalCode(int postalCode, Serializable county, Serializable district) {
		this.postalCode = postalCode;
		this.county = county;
		this.district = district;
	}

	public int getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}

	public Serializable getCounty() {
		return this.county;
	}

	public void setCounty(Serializable county) {
		this.county = county;
	}

	public Serializable getDistrict() {
		return this.district;
	}

	public void setDistrict(Serializable district) {
		this.district = district;
	}

}
