package com.erp.demo.model;
// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

import java.sql.Timestamp;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * Dispatchment generated by hbm2java
 */
@Entity
public class Dispatchment implements java.io.Serializable {
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer did;
	private String oid;
	private String dispEid1;
	private String dispEid2;
	private char status;
	@CreatedDate()
	private Timestamp createTime;
	// 修改時自動創建時間
	@LastModifiedDate
	private Timestamp updateTime;
	@LastModifiedBy
	private String updateName;

	public Dispatchment() {
	}

	public Dispatchment( Integer did,String oid, String dispEid1, String dispEid2, char status, Timestamp createTime,
			Timestamp updateTime, String updateName) {
		this.did = did;
		this.oid = oid;
		this.dispEid1 = dispEid1;
		this.dispEid2 = dispEid2;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.updateName = updateName;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public String getDispEid1() {
		return this.dispEid1;
	}

	public void setDispEid1(String dispEid1) {
		this.dispEid1 = dispEid1;
	}

	public String getDispEid2() {
		return this.dispEid2;
	}

	public void setDispEid2(String dispEid2) {
		this.dispEid2 = dispEid2;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Timestamp getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}

	public String getUpdateName() {
		return this.updateName;
	}

	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

}
