package com.erp.demo.model;
// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

/**
 * EmRole generated by hbm2java
 */
public class EmRole implements java.io.Serializable {

	private String roleCode;
	private String roleName;
	private char memberSelectR1;

	public EmRole() {
	}

	public EmRole(String roleCode, String roleName, char memberSelectR1) {
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.memberSelectR1 = memberSelectR1;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public char getMemberSelectR1() {
		return this.memberSelectR1;
	}

	public void setMemberSelectR1(char memberSelectR1) {
		this.memberSelectR1 = memberSelectR1;
	}

}
