package com.erp.demo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;

// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

/**
 * PostalCode generated by hbm2java
 */
@Entity
public class PostalCode implements java.io.Serializable {
	@Id
	private Integer postalCode;
	@Column(length=10)
	private String county;
	@Column(length=50)
	private String district;

	public PostalCode() {
	}

	public PostalCode(Integer postalCode, String county, String district) {
		this.postalCode = postalCode;
		this.county = county;
		this.district = district;
	}

	public int getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

}
