package com.erp.demo.model;
// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

/**
 * PostalCode generated by hbm2java
 */
public class PostalCode implements java.io.Serializable {

	private int postalCode;
	private String county;
	private String district;

	public PostalCode() {
	}

	public PostalCode(int postalCode, String county, String district) {
		this.postalCode = postalCode;
		this.county = county;
		this.district = district;
	}

	public int getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

}
