package com.erp.demo.model.physical;
// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

import java.sql.Timestamp;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Dispatchment generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Dispatchment implements java.io.Serializable {
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer did;
	private Integer oid;
	private String dispEid1;
	private String dispEid2;
	private char status;
	@CreatedDate()
	private Timestamp createTime;
	// 修改時自動創建時間
	@LastModifiedDate
	private Timestamp updateTime;
	@LastModifiedBy
	private String updateName;

}
