package com.erp.demo.model.physical;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

/**
 * EmDepartment generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class EmDepartment implements java.io.Serializable {
	@Id
	@Column(length=45)
	private String departmentCode;
	@Column(length=100)
	private String departmentName;
	@Column(length=100)
	private String jobTitle;

}
