package com.erp.demo.model.physical;
// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.sql.Timestamp;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
//對應資料庫表名稱
@Table(schema = "dbo", name = "Employee")
public class Employee {

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "EID")
	private Integer EID;
	
	private String username;
	private String password;
	private String name;
	private String departmentCode;
	private String roleCode;
	private String sex;

	@Column(name = "NationalId", columnDefinition = "char(10)")
	private String nationalId;

	private Date birthDate;
	private String cellphone;
	private String landlineprefix;
	private String landline;
	private String email;
	private byte postalCode;
	private String address;
	private String footnote;

	// 創建時間(好像不會Work...)
	@CreatedDate()
	private Timestamp createTime;

	// 修改時間(好像不會Work...)
	@LastModifiedDate
	private Timestamp updateTime;

	@LastModifiedBy
	private String updateName;

	public Employee() {
	}

	public Employee(Integer eid, String username, String password, String name, String departmentCode,
			String roleCode, String sex, String nationalId, Date birthDate, String cellphone, String landlineprefix,
			String landline, String email, byte postalCode, String address, String footnote, Timestamp createTime,
			Timestamp updateTime, String updateName) {
		this.EID = eid;
		this.username = username;
		this.password = password;
		this.name = name;
		this.departmentCode = departmentCode;
		this.roleCode = roleCode;
		this.sex = sex;
		this.nationalId = nationalId;
		this.birthDate = birthDate;
		this.cellphone = cellphone;
		this.landlineprefix = landlineprefix;
		this.landline = landline;
		this.email = email;
		this.postalCode = postalCode;
		this.address = address;
		this.footnote = footnote;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.updateName = updateName;
	}



	public Integer getEID() {
		return EID;
	}

	public void setEID(Integer eID) {
		EID = eID;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDepartmentCode() {
		return this.departmentCode;
	}

	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getNationalId() {
		return this.nationalId;
	}

	public void setNationalId(String nationalId) {
		this.nationalId = nationalId;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getLandlineprefix() {
		return this.landlineprefix;
	}

	public void setLandlineprefix(String landlineprefix) {
		this.landlineprefix = landlineprefix;
	}

	public String getLandline() {
		return this.landline;
	}

	public void setLandline(String landline) {
		this.landline = landline;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public byte getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(byte postalCode) {
		this.postalCode = postalCode;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getFootnote() {
		return this.footnote;
	}

	public void setFootnote(String footnote) {
		this.footnote = footnote;
	}

	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Timestamp getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}

	public String getUpdateName() {
		return this.updateName;
	}

	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

}
