package com.erp.demo.model.physical;
// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.sql.Timestamp;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Employee generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
//對應資料庫表名稱
@Table(schema = "dbo", name = "Employee")
public class Employee {

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "EID")
	private Integer eid;
	
	private String username;
	private String password;
	private String name;
	private String departmentCode;
	private String roleCode;
	private String sex;

	@Column(name = "NationalId", columnDefinition = "char(10)")
	private String nationalId;

	private Date birthDate;
	private String cellphone;
	private String landlineprefix;
	private String landline;
	private String email;
	private byte postalCode;
	private String address;
	private String footnote;

	// 創建時間(好像不會Work...)
	@CreatedDate()
	private Timestamp createTime;

	// 修改時間(好像不會Work...)
	@LastModifiedDate
	private Timestamp updateTime;

	@LastModifiedBy
	private String updateName;

	public Timestamp getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Timestamp getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}

	
}
