package com.erp.demo.model.physical;
// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.sql.Timestamp;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Member generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Member implements java.io.Serializable {
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="MID")
	private Integer mid;
	@Column(length=255,unique=false)
	private String username;
	@Column(length=255)
	private String password;
	@Column(length=45)
	private String name;
	@Column(length=1)
	private String sex;
	
	@Column(name = "NationalId", columnDefinition = "char(10)")
	private String nationalId;
	
	private Date birthDate;

	private String cellphone;
	@Column(length=4)
	private String landlineprefix;
	@Column(length=8)
	private String landline;
	@Column(length=255)
	private String email;
	private byte postalCode;
	private String address;
	private String footnote;
	@CreatedDate()
	private Timestamp createTime;
	// 修改時自動創建時間
	@LastModifiedDate
	private Timestamp updateTime;
	@LastModifiedBy
	@Column(length=45)
	private String updateName;
	
	public Integer getMid() {
		return mid;
	}
	public void setMid(Integer mid) {
		this.mid = mid;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getNationalId() {
		return nationalId;
	}
	public void setNationalId(String nationalId) {
		this.nationalId = nationalId;
	}

	
	
}
