package com.erp.demo.model.physical;
// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

import java.time.LocalDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.erp.demo.model.nonphysical.AbstractAuditable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Member generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@EntityListeners(AuditingEntityListener.class)
public class Member extends AbstractAuditable implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MID")
	private Integer mid;
	@Column(length = 255, unique = false)
	private String username;
	@Column(length = 255)
	private String password;
	@Column(length = 45)
	private String name;
	@Column(length = 1)
	private String sex;

	@Column(name = "NationalId", columnDefinition = "char(10)")
	private String nationalId;

	private LocalDate birthDate;

	private String cellphone;
	@Column(length = 4)
	private String landlineprefix;
	@Column(length = 8)
	private String landline;
	@Column(length = 255)
	private String email;
	private byte postalCode;
	private String address;
	private String footnote;

}
