package com.erp.demo.model.physical;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

/**
 * OrderItem generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class OrderItem implements java.io.Serializable {
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	private String oid;
	private String pid;
	private int quantity;

}
