package com.erp.demo.model.physical;
// Generated 2024�~3��2�� �U��7:02:46 by Hibernate Tools 6.3.1.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * Ostatus generated by hbm2java
 */
@Entity
public class OStatus implements java.io.Serializable {
	@Id
	private Integer ostatusCode;
	@Column(length=100)
	private String ostatusName;
	@Column(length=255)
	private String ostatusDesc;

	public OStatus() {
	}

	public OStatus(Integer ostatusCode, String ostatusName, String ostatusDesc) {
		this.ostatusCode = ostatusCode;
		this.ostatusName = ostatusName;
		this.ostatusDesc = ostatusDesc;
	}

	public int getOstatusCode() {
		return this.ostatusCode;
	}

	public void setOstatusCode(int ostatusCode) {
		this.ostatusCode = ostatusCode;
	}

	public String getOstatusName() {
		return this.ostatusName;
	}

	public void setOstatusName(String ostatusName) {
		this.ostatusName = ostatusName;
	}

	public String getOstatusDesc() {
		return this.ostatusDesc;
	}

	public void setOstatusDesc(String ostatusDesc) {
		this.ostatusDesc = ostatusDesc;
	}

}
